name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Lets
        uses: lets/lets-action@v1
        with:
          version: v0.0.45
      - run: lets --version
      - run: docker-compose --version
      - run: lets test
